datasource:
  development:
    username: username
    password: password
    url: jdbc:h2:./project72DataBaseH2
  production:
    username: username
    password: password
    url: jdbc:postgresql:./project72DataBasePostgres

ebean:
  migration:
    run: true